---
name: ((deployment_name))

releases:
- name: mongodb-services
  version: latest

update:
  canaries: 1
  canary_watch_time: 30000-240000
  update_watch_time:  30000-240000
  max_in_flight: 1 #<-- important to limit max in flight
  serial: false

stemcells:
- alias: ubuntu
  os: ubuntu-xenial
  version: latest

instance_groups:
- name: mongod
  azs: [z1]
  instances: 3
  vm_type: default
  env:
    bosh:
      swap_size: 0
    persistent_disk_fs: xfs
  stemcell: ubuntu
  networks:
    - name: default
  persistent_disk_type: default
  jobs:
  - name: mongod
    release: mongodb-services
    properties:
      server_certificate:
        certificate: ((mongo_ca.certificate))
        private_key: ((mongo_ca.private_key))
      replication:
        replica_set_name: mongo-data-shared
      users:
      - name: root
        password: ((root_password))
        roles:
        - role: root
          db: admin
      - name: admin
        password: ((admin_password))
        roles:
        - role: userAdminAnyDatabase
          db: admin

variables:
- name: admin_password
  type: password
- name: root_password
  type: password
- name: mongo_ca
  type: certificate
  options:
    is_ca: true
    common_name: MongoDB CA