name: ((deployment_name))

releases:
- name: &mongodb_release ((release_name))
  version: latest

update:
  canaries: 1
  canary_watch_time: 30000-240000
  update_watch_time:  30000-240000
  max_in_flight: 1 #<-- important to limit max in flight
  serial: false

stemcells:
- alias: &stemcell ubuntu
  os: ubuntu-xenial
  version: latest

instance_groups:
- name: cfgsvr
  release: *mongodb_release
  azs: [z1]
  instances: 3
  vm_type: default
  env:
    bosh:
      swap_size: 0
  stemcell: *stemcell
  networks:
  - name: default
  persistent_disk_type: default
  env:
    persistent_disk_fs: xfs
  jobs:
  - name: bpm
    release: bpm
  - name: cfgsvr
    release: *mongodb_release
    properties:
      port: 23758
      replication:
        replica_set_name: mongo-config
      server_certificate:
        certificate: ((mongo_ca.certificate))
        private_key: ((mongo_ca.private_key))
  - name: mongos
    release: *mongodb_release
    properties:
      server_certificate:
        certificate: ((mongo_ca.certificate))
        private_key: ((mongo_ca.private_key))
      users:
      - name: root
        password: ((root_password))
        roles:
        - role: root
          db: admin
      - name: admin
        password: ((admin_password))
        roles:
        - role: userAdminAnyDatabase
          db: admin

- name: shard-0
  release: *mongodb_release
  azs: [z1]
  instances: 3
  vm_type: default
  env:
    bosh:
      swap_size: 0
  stemcell: *stemcell
  networks:
  - name: default
  persistent_disk_type: default
  env:
    persistent_disk_fs: xfs
  jobs:
  - name: shardsvr
    release: *mongodb_release
    properties:
      server_certificate:
        certificate: ((mongo_ca.certificate))
        private_key: ((mongo_ca.private_key))
      replication:
        replica_set_name: mongo-data-shared
      users:
      - name: root
        password: ((root_password))
        roles:
        - role: root
          db: admin

variables:
- name: admin_password
  type: password
- name: root_password
  type: password
- name: mongo_ca
  type: certificate
  options:
    is_ca: true
    common_name: MongoDB CA