instance_groups:
- azs:
  - z1
  - z2
  - z3
  env:
    persistent_disk_fs: xfs
  instances: 3
  env:
    persistent_disk_fs: xfs
  jobs:
  - name: bpm
    release: bpm
  - name: cfgsvr
    release: mongodb-services
    properties:
      admin_password: myP@ssword
      admin_username: smarsh
      port: 23758
      replication:
        replica_set_name: mongo-config-shared
      root_password: rootpassword
      root_username: root
      server_certificate:
        certificate: ((mongo_ca.certificate))
        private_key: ((mongo_ca.private_key))
  name: mdbconf-shared
  networks:
  - name: default
  release: mongodb-services
  stemcell: ubuntu
  vm_type: default
- azs:
  - z1
  - z2
  - z3
  instances: 1
  jobs:
  - name: bpm
    release: bpm
  - name: mongos
    release: mongodb-services
    properties:
      server_certificate:
        certificate: ((mongo_ca.certificate))
        private_key: ((mongo_ca.private_key))
      users:
      - name: root
        password: ((root_password))
        roles:
        - role: root
          db: admin
      - name: admin
        password: ((admin_password))
        roles:
        - role: userAdminAnyDatabase
          db: admin
  name: mongos-shared
  networks:
  - name: default
  stemcell: ubuntu
  vm_type: default
- azs:
  - z1
  - z2
  - z3
  env:
    persistent_disk_fs: xfs
  instances: 3
  jobs:
  - name: bpm
    release: bpm
  - name: shardsvr
    release: mongodb-services
    properties:
      server_certificate:
        certificate: ((mongo_ca.certificate))
        private_key: ((mongo_ca.private_key))
      replication:
        replica_set_name: mongo-data-shared
      users:
      - name: root
        password: ((root_password))
        roles:
        - role: root
          db: admin
  name: mdb-shared
  networks:
  - name: default
  release: mongodb-services
  stemcell: ubuntu
  vm_type: default

- name: acceptance_tests
  lifecycle: errand
  azs: [z1]
  instances: 1
  vm_type: default
  stemcell: ubuntu
  networks:
  - name: default
  jobs:
  - name: mongodb-acceptance-tests
    release: mongodb-services
    properties:
      mongo_test_suite: [ readwrite, replicaset ]
name: mongodb
releases:
- name: mongodb-services
  version: latest
- name: "bpm"
  version: "1.0.4"
  url: "https://bosh.io/d/github.com/cloudfoundry-incubator/bpm-release?v=1.0.4"
  sha1: "41df19697d6a69d2552bc2c132928157fa91abe0"
stemcells:
- alias: ubuntu
  os: ubuntu-xenial
  version: latest
update:
  canaries: 1
  canary_watch_time: 30000-240000
  max_in_flight: 1
  serial: false
  update_watch_time: 30000-240000
variables:
  - name: root_password
    type: password
  - name: keyfile_content
    type: password
    options:
      length: 200
  - name: mongo_ca
    type: certificate
    options:
      is_ca: true
      common_name: MongoDB CA
features:
  use_dns_addresses: false
